config/routes.rb
Rails.application.routes.draw do
  resources :contact
  get 'contact/index' => 'contact#index'

  resources :about
  get 'about/index' => 'about#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issues, only: [:show, :index]
  resources :ballots, only: [:show, :index]
  resources :votes, only: [:new, :create]
  root 'home#index'
  resources :registrations
  get 'resources' => 'home#resources'
  
  resources :votes, only: [:index]  
  get 'votes/results' => 'votes#results'
  get 'votes/thanks_for_voting' => 'votes#thanks_for_voting'
  
  namespace :admin do
    resources :issues
  end

  namespace :api do
    resources :issues
    resources :votes
    resources :voters
    resources :schools
  end

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :issue
  has_many :votes
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :issue_type
  has_many :choices
  has_many :issue_links
end

app/models/issue_link.rb
class IssueLink < ActiveRecord::Base
  belongs_to :issue
end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter
  belongs_to :choice
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :school
  has_many :votes

  def self.build_authenticated
    create!(authenticated: true, registration_number: RegistrationNumber.next)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    @issue = Issue.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    
    @issue = Issue.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if session[:voter]
      redirect_to action: 'show', id: 1
    else
      # renders the registration page
      @voter = Voter.new
      @schools = School.all.map { |s| [s.name, s.id] }
    end
  end

  def create
    # 1. Try submitting the test form at /registrations/new and hitting this breakpoint. (explore the 'params' variable)
    # binding.pry

    voter = nil

    # 2. Implement the 'unauthenticated voter' scenario - where the voter needs to be created without a registration number
    if registration_number.blank?
      voter = Voter.create!(voter_params.merge(registration_number: RegistrationNumber.next))
    else
      # 3. Implement the 'authorized voter' scenario - where the voter has a valid registration number.
      voter = Voter.find_by(registration_number: registration_number, school_id: voter_params[:school_id])
      voter.update_attributes!(voter_params)
    end

    # 4. Store the registered user in 'session' (we can discuss what session is)
    session[:voter] = voter
    redirect_to action: 'show', id: 1
  end

  # renders the success page
  def show
    # TODO - Get the registered user from session if present
    @voter = session[:voter]
  end

  private

  def registration_number
    params[:voter][:registration_number]
  end

  def voter_params
    params.require(:voter).permit(:school_id, :gender, :school_year, :will_be_eighteen)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new

    unless session[:voter]
      redirect_to new_registration_path
    else
      @voter = Voter.find_by(session[:voter]['id'])
      @issues = Issue.all
      @national_issues = Issue.joins(:issue_type)
                              .where(issue_types: {national: true})
                              .all
      @state_issues = Issue.joins(:issue_type)
                           .where(issue_types: {state: true})
                           .all
    end
  end
  def create
    voter = Voter.find(params[:voter_id])
    voter.votes.destroy_all
    if issue_params
      issues = Issue.where(id:params[:issue].keys)
      choices = issues.map{|i|i.choices.where(id:params[:issue][i.id.to_s])}.flatten
      choices.each do |choice|
        issue_id = choice.issue_id.to_s
        Vote.create!(
          voter_id: voter.id,
          choice_id: choice.id,
          understand_this: understand_this_params[issue_id],
          care_about_this: care_about_this_params[issue_id]
        )
      end
    end
  end
  def thanks_for_voting
  end

  def results
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
  end

  private

  def issue_params
    params.require(:issue)
  end

  def understand_this_params
    params.require(:understand_this)
  end

  def care_about_this_params
    params.require(:care_about_this)
  end

  def index
    @issues = Issue.all
  end

  def voter
    Voter.find_by(session[:voter]['id'])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ballots/index.html.erb
<!--This is the Sample Ballot page-->
<h1 style="text-align: left" ; color="blue">Sample Ballot</h1>
<!--Gives directions to users about the web page-->
<p>This is a sample ballot containing all national and state issues and possible candidates. For more information, click on the question mark.</p>
<p>When you are ready to vote, click the "Vote Now" button- But make sure you've registered first!</p>
<style>
/*Styles the image to be a certain size*/
.img {
	width: '40px';
	border-style: none;
	height: '200px';
}
/*Scales the question circle 20% on hover*/
.fa-question-circle:hover {
	-webkit-transform: scale(1.2);
}
/*Scales the image for the choice 5% on hover*/
.choice:hover {
	-webkit-transform: scale(1.05);
}

.fa-question-circle {  
	transition: font-size 0.35s ease; 
}
/*Modifies the slick slide bar, places it in the center of the page*/
.slick-prev:before, .slick-next:before{
    color:#333;
}
.slick-slide img {
	margin-left: auto;
	margin-right: auto;
}
.slick-slide {
	text-align: center;
}
/*Modifies the tooltip on hover over the image of the choice*/
.tooltip {
    position: relative;
    display: inline-block;
    border-bottom: 1px dotted black;
}

.tooltip .tooltiptext {
    visibility: hidden;
    width: 120px;
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 0;

    /* Position the tooltip */
    position: absolute;
    z-index: 1;
}

.tooltip:hover .tooltiptext {
    visibility: visible;
}

</style>

<script>
$(function() {
	/* javascript & jquery goes in a script block, you can keep it here */
	/*Incorporate slick code, puts the slide bar in place on the webpage*/
	$('.choice-list').slick({
  		dots: true,
  		infinite: true,
  		speed: 300,
 		slidesToShow: 4,
  		slidesToScroll: 4,
  		responsive: [
		    {
			    breakpoint: 1024,
			    settings: {
				    slidesToShow: 3,
				    slidesToScroll: 3,
				    infinite: true,
				    dots: true
		      }
		    },
		    {
		      	breakpoint: 600,
		      	settings: {
			        slidesToShow: 2,
			        slidesToScroll: 2
			      }
		    },
		    {
	      	breakpoint: 480,
	      	settings: {
		        slidesToShow: 1,
		        slidesToScroll: 1
		      }
		    }
		  ]
		});
	});
</script>

<!--Separates the National and State Issues provided to us from the Issues team. Makes each issue have choices-->
<h1>National Issues</h1>
<% @national_issues.each do |issue| %>
	<div class="row">
		<div class="col-md-12">
			<h2>
		      <%= issue.title %>
		      <%= link_to ballot_path(issue) do %>
		      	<i class="fa fa-question-circle"></i>
		      <% end %>
		    </h2>
		</div>
	</div>
	<div class="choice-list">
		<% issue.choices.each do |choice| %>
			<div class="choice" title="<%= choice.title %>">
				<%= image_tag(choice.image_url, width: '100px', alt: choice.title, class: 'img-responsive') %>
				<br/>
				<%= choice.title %>
			</div>
		<% end %>
	</div>
<% end %>
<br/>
<br/>
<br/>
<!--State issues and their choices-->
<h1>State Issues</h1>
<% @state_issues.each do |issue| %>
	<div class="row">
		<div class="col-md-12">
			<h2>
		      <%= issue.title %>
		      <%= link_to ballot_path(issue) do %>
		      	<i class="fa fa-question-circle"></i>
		      <% end %>
		    </h2>
		</div>
	</div>
	<div class="choice-list">
		<% issue.choices.each do |choice| %>
			<div class="choice" title="<%= choice.title %>">
				<%= image_tag(choice.image_url, width: '100px', alt: choice.title, class: 'img-responsive') %>
				<br/>
				<%= choice.title %>
			</div>
		<% end %>
	</div>
<% end %>
<!--Button that directs users to the Vote Now/ Ballt Page-->
<h1 style="text-align: left" ;><%= link_to "Vote Now", new_vote_path, class: "btn btn-default"%></h1>
<br/>

app/views/ballots/show.html.erb
<h1 style="text-align: left">Sample Ballot</h1>
<h2><%= @issue.title %></h2>
<p><%= @issue.description %></p>
<h3>Choices</h3>
<ul>
  <% @issue.choices.each do |choice| %>
    <li>
      <%= choice.title %>
      <% unless choice.party.nil? %>
      <ul>
        <li>
          Party:<%= choice.party %>
        </li>
      </ul>
      <% end %>
    </li>
  <% end %>
</ul>