config/routes.rb
Rails.application.routes.draw do
  resources :contact
  get 'contact/index' => 'contact#index'

  resources :about
  get 'about/index' => 'about#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issues, only: [:show, :index]
  resources :ballots, only: [:show, :index]
  resources :votes, only: [:new, :create]
  root 'home#index'
  resources :registrations
  get 'resources' => 'home#resources'
  
  resources :votes, only: [:index]  
  get 'votes/results' => 'votes#results'
  get 'votes/thanks_for_voting' => 'votes#thanks_for_voting'
  
  namespace :admin do
    resources :issues
  end

  namespace :api do
    resources :issues
    resources :votes
    resources :voters
    resources :schools
  end

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :issue
  has_many :votes
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :issue_type
  has_many :choices
  has_many :issue_links
end

app/models/issue_link.rb
class IssueLink < ActiveRecord::Base
  belongs_to :issue
end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter
  belongs_to :choice
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :school
  has_many :votes

  def self.build_authenticated
    create!(authenticated: true, registration_number: RegistrationNumber.next)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    @issue = Issue.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    
    @issue = Issue.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if session[:voter]
      redirect_to action: 'show', id: 1
    else
      # renders the registration page
      @voter = Voter.new
      @schools = School.all.map { |s| [s.name, s.id] }
    end
  end

  def create
    # 1. Try submitting the test form at /registrations/new and hitting this breakpoint. (explore the 'params' variable)
    # binding.pry

    voter = nil

    # 2. Implement the 'unauthenticated voter' scenario - where the voter needs to be created without a registration number
    if registration_number.blank?
      voter = Voter.create!(voter_params.merge(registration_number: RegistrationNumber.next))
    else
      # 3. Implement the 'authorized voter' scenario - where the voter has a valid registration number.
      voter = Voter.find_by(registration_number: registration_number, school_id: voter_params[:school_id])
      voter.update_attributes!(voter_params)
    end

    # 4. Store the registered user in 'session' (we can discuss what session is)
    session[:voter] = voter
    redirect_to action: 'show', id: 1
  end

  # renders the success page
  def show
    # TODO - Get the registered user from session if present
    @voter = session[:voter]
  end

  private

  def registration_number
    params[:voter][:registration_number]
  end

  def voter_params
    params.require(:voter).permit(:school_id, :gender, :school_year, :will_be_eighteen)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new

    unless session[:voter]
      redirect_to new_registration_path
    else
      @voter = Voter.find_by(session[:voter]['id'])
      @issues = Issue.all
      @national_issues = Issue.joins(:issue_type)
                              .where(issue_types: {national: true})
                              .all
      @state_issues = Issue.joins(:issue_type)
                           .where(issue_types: {state: true})
                           .all
    end
  end
  def create
    voter = Voter.find(params[:voter_id])
    voter.votes.destroy_all
    if issue_params
      issues = Issue.where(id:params[:issue].keys)
      choices = issues.map{|i|i.choices.where(id:params[:issue][i.id.to_s])}.flatten
      choices.each do |choice|
        issue_id = choice.issue_id.to_s
        Vote.create!(
          voter_id: voter.id,
          choice_id: choice.id,
          understand_this: understand_this_params[issue_id],
          care_about_this: care_about_this_params[issue_id]
        )
      end
    end
  end
  def thanks_for_voting
  end

  def results
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
  end

  private

  def issue_params
    params.require(:issue)
  end

  def understand_this_params
    params.require(:understand_this)
  end

  def care_about_this_params
    params.require(:care_about_this)
  end

  def index
    @issues = Issue.all
  end

  def voter
    Voter.find_by(session[:voter]['id'])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/api/votes_helper.rb
module Api::VotesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/about/index.html.erb
<h1>About CLETeenVote</h1>
<style>
#Lawyers{
    width:180px;
    height:150px;}
#west{
    width:150px;
    height:150px;}
#csu{
    width:200px;
    height:150px;}
#cleveland{
    width:300;
    height:150;}
#wcci{
    width:490;
    height:150;
}
.sponsor{
    width:auto;
    height:auto;}

.boxed {
  border: 3px solid black;
  font-size:26px;
}

</style>

    <!--bootstrap grid-->
<div class="container"> <!--holds your stuff!-->
    <div class="row">
        <p>Various high schools created a section of the app. Each high school was required to take different steps to develop their pages. <br /> The app teen vote introduces teens to civic engagement which allows them to improve conditions for others and help shape the communities future.
    </p>
    </div>
    <!--
     <div class="row">
         <div class="boxed col-md-6">
            <a href="#JohnMarshallIT">John Marshall IT</a> <br />
            <a href="#Shaw">Shaw</a><br />
            <a href="#Beaumont">Beaumont</a><br />
            <a href="#West shore tech">West Shore Tech</a><br />
            <a href="#JaneAddams">Jane Addams</a><br/>
        </div>
    </div> -->
    
      <div class="row">
   
            <div class="col-md-12">
                <h1>John Marshall IT</h1>
        
            </div>
  
      </div> 

    <a name="johnmarshallit" />
    <div class="row">
    <div class="col-md-4">
              <a href="http://www.wescheme.org/view?publicId=hGvz6VxLhx" target="_blank"><img src="/assets/johnMarshall/marshall.jpg" id="Lawyers" alt="John Marshall High School"/></a>
    </div>
    <div class="col-md-8">
        <h3>Team: We Are "IT" </h3>
        <p>John Marshall School of Information Technology is creating the About and Contant Us page. Viewers will be able to learn about how the app came to be and how each school participated to contruct the overall results. </p>
    </div>
    </div>
    
    <div class="row">
       <div class="col-md-12">
            <h1>Jane Addams</h1>
        </div>
    </div> 

      <a name="JaneAddams" />

    <div class="row">
       <div class="col-md-4">
          <img src="/assets/johnMarshall/addams.png" alt="Jane Addams High School"/>
        </div>
          <div class="col-md-8">
              <h3>Team: Kidz Next Door <br> Team: Digital Destroyers</h3>
             <p> Hello, this is Jane Addams business career center.
                We aren't really a coding type of school, we're strictly business but we decided to try something new, which is coding.   
                So far its been light weight and complicated but we are getting used to it.
                We decided to split into two teams which are kidz next door (to tri-c), and digital destroyers.
                The kidz next door focused on the homepage, and digital destroyers focused on our resources.
            </p>
          </div>
     
      </div>
      <div class="row">
              <div class="col-md-12">
                <h1>Shaw</h1>
              </div>
          </div> 

    <a name="Shaw" />
    <div class="row">
      
       <div class="col-md-4">
              <img src="/assets/johnMarshall/shaw.png" alt="Shaw High School"/>
              </div>
              <div class="col-md-8">
                  <h3>Team: Shaw <br> Team: Cardinals</h3>
                 <p> At Shaw High School in Mr. Dutton's Computer Science class we have been working on learning to code using 
                    Scratch and a variety of other technologies like HTML, CSS and JavaScript.  The issues team has been picking 
                    the different issues and looking up the different ways we could have the issues presented. We liked the idea 
                    of having a short video to accompany each issue to make it easier for the "voters" to understand.
                    
                    On the registration team, we have learned how to use Cloud9, Slack for communication and Ruby on Rails. We have learned how to program options 
                    for gender, age, school and more, including how to save all of the information in one place. Also, some of us have 
                    learned how to design databases using SQL!
                 </p>
              </div>
              </div>
              
              <div class="col-md-12">
            <h1>Beaumont</h1>
            
        </div>

<a name="Beaumont" />
<div class="row">
  
   <div class="col-md-4">
          <img src="/assets/johnMarshall/beaumont_school.jpg" alt="Beaumont School"/>
          </div>
          <div class="col-md-8">
              <h3>Team: Be@uTech</h3>
             <p>Beaumont School’s team Be@uTech is run by six juniors; Alex Andrus, Kimberly Browske, 
                Lindsey Clark, Alex Danford, Emma Rubadue, and Margaret Schiffer, and one senior, Josie Zucca. 
                We founded our club in 2014 to more fully integrate technology into daily life at Beaumont, as well as to promote 
                female presence in the world of technology. This project gave us the opportunity to fulfill our mission. Our team has 
                been working hard to complete our tasks of the Vote Now and Ballot pages. While our team had some difficulties, we worked hard to 
                “do it and make it better,” using Ruby, CSS, AND HTML. We would like to thank our moderators Sr. Ann and Mrs. Santo and our mentors, 
                Stephanie Gandy and Joel Byler for all their help, which was integral to our success in this project.
            </p>
          </div>
          </div>
          
           <div class="col-md-12">
        <h1>West Shore Tech</h1>
        
        </div>
  
<a name="West shore tech" />
<div class="row">
  
   <div class="col-md-4">
          <img src="/assets/johnMarshall/WestShore.jpg" id="west" alt="Lakewood City Schools"/>
          </div>
          <div class="col-md-8">
              <h3>Team: Lakewood Code Rangers</h3>
             <p> West Shore Tech took on the development of the Results and the "I Voted pages. The Lakewood Code Rangers learned how to make webpages starting from a wireframe and progressing into the first iteration.
             We divided our team into three teams: JavaScript, Design, and HTML based on our skills. As a team, we learned about JavaScript, Bootstrap, HTML, CSS and APIs.</p>
          </div>
           
         </div>
         
<div class="row">
    <div class="col-md-2">
        <a href="https://www.att.com" target="_blank">
        
    <img class="img-responsive" src="assets/image/att_globe_200-1.png" alt="ATT" />
    </a>
    </div>
    <div class="col-md-2">
    <a href="http://wecancodeit.org/"  target="_blank" />
    <img class="img-responsive" src="assets/image/WCCIT-logo-notag-600.png" id="wcci" alt="We Can Code IT"/>
    </a>
    </div>
    <div class="col-md-2">
    
    <a href="http://www.tri-c.edu" target="_blank" /> 
    <img class="img-responsive" src="assets/image/tri-c.jpg" alt="Cuyahoga Community College" /> 
    </a>
    </div>
    <div class="col-md-2">
    
    <a href="https://www.juniorachievement.org/web/ja-grcleveland"  target="_blank">
    <img class="img-responsive" src="assets/image/JAGreaterClevelandPro.gif" alt="Junior Achievement" />
    </a>
    </div>
    <div class="col-md-2">
    
    <a href="http://www.csuohio.edu"  target="_blank">
    <img class="img-responsive" src="assets/image/csu.jpg" id="cleveland" alt="Cleveland State University" />
    </a>
    </div>
    <div class="col-md-2">
    <a href="http://www.thisiscleveland.com"  target="_blank">
    <img class="img-responsive" src="assets/image/logo-destination_cleveland.jpg" alt="This is Cleveland"/>
    </a>
    </div>
    
</div>
   
   
</div>

app/views/contact/index.html.erb
<h1>Contact Us</h1>
 <head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">
</head>
<style type="text/css">
    .box {
        height:40px;
        width:40px;
        color:white;
        font-size:36px;
        background-color:#ff0000;
        float:left;
        display:block;
    }
    
    .link {
        display:block;
        float:right;
    }
    
    .feeling {color:red;
        font-family:cursive;
        
    }
    .hello{ font-size: 18;
        color: blue;
        font-family:Arial Black;
        
    }
    
    .schoollink {
        font-size: ;
    }
    h1 {
        text-align :center;
    }
.schools{
    font-size:30px;
    text-align:center;
    
}

.ui-slider{ 
    width: 400px; height: 15px; 
    
}


.col-md-9{
    border-radius: 25px;
    border: 2px solid #C0C0C0;
    padding: 20px;
    width: 500px;
    text-align: center;

}
.col-md-3{
    margin: 50px;
}

textarea {
   resize: none;
   width: 400px;
}
form{
    font-size: 75%;
}


</style>

 <script>
  $(function() {
    $( "#slider" ).slider({
      width:75,
      height:10,
      min: 1,
      max: 5,
      step: 1,
      slide: function( event, ui ) {
        $( "#amount" ).val(  ui.value );
      }
    });
    $( "#amount" ).val(  $( "#slider" ).slider( "value" ) );
  });
  </script>
</head>




           

    
    <!--form/school-->
<div class="container">
        <div class= "col-md-9">

    
    <!-- form --->    
        <form class=hello 
        action="MAILTO:CleTeenHack@WeCanCodeIT.org." method="post" enctype="text/plain">
      First Name:<br>
      <input type="text" name="firstname"><br>
      Last Name:<br>
      <input type="text" name="lastname"><br>
      Email:<br>
      <input type="text" name="email">
      <br>
      Phone Number:<br>
      <input type="text" name="phonenumber"><br>
     
  Contact Subject:<br>
  <input type="text" name="Contactsubject"><br>
  Comment:<br>
   <textarea rows="4" cols="50">
        Write Your Comments Here! 
   </textarea> <br><br>
 <p class="feeling"> 
      
      <label for="amount">How Are You Feeling?<br>
     "5" being Bad and "1" being Awesome!
      </label>
       <br>
      <img src="assets/image/emoji-f-up.png" alt="HTML5 Icon" width="410.5" height="70">
      <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;"> <br>
    
    </p>
         
    <div id="slider"></div>
   <input type="submit" value="Submit">


  </form>
  <!-- end of form -->
  </div>
  
    <div class="col-md-3">
   
       <h2><u>Schools</u></h2>
   
       <img width="35" src= "assets/johnMarshall/marshall.jpg"/>&nbsp;<a href="http://www.clevelandmetroschools.org/Page/2217" target="_blank" class="schools">John Marshall</a><br/>
       <img width="30" src= "assets/johnMarshall/shaw.png"/>&nbsp;<a href="http://www.east-cleveland.k12.oh.us/school_home.aspx?schoolID=12"  target="_blank" class="schools">Shaw</a><br/>
       <img width="30" src= "assets/johnMarshall/addams.png"/>&nbsp;<a href="http://www.clevelandmetroschools.org/addamsbcc"  target="_blank" class="schools">Jane Addams</a><br/>
       <img width="30" src= "assets/johnMarshall/beaumont_school.jpg"/>&nbsp;<a href="http://www.beaumontschool.org/"  target="_blank" class="schools">Beaumont</a><br/>
       <img width="30" src= "assets/johnMarshall/WestShore.jpg"/>&nbsp;<a href="http://www.cleveland.com/westlake/index.ssf/2015/12/west_shore_chatter_rocky_river_4.html" class="schools" target="_blank" >West Shore</A><br/>
     <br>
     <br>
        <a href="https://www.facebook.com/cleteenhack" target="_blank" > <img width="100" src= "assets/image/fb.png"/></a>&nbsp;
        <a href="https://www.instagram.com/cleteenhack" target="_blank" > <img width="20" src= "assets/johnMarshall/Instagram.png"/></a>&nbsp;
        <a href="https://www.twitter.com/cleteenhack" target="_blank" > <img width="20" src= "assets/image/Twitter.png"/></a>
    </div>
</div>

app/views/home/index.html.erb
<h1>CLETeenVote: Cleveland Teen Civic Engagement. Teens, be heard! #CLETeenHack</h1>
<div class="container-fluid">
 

<!--this is our large picture-->
    <div class="row">
        <div class="col-md-12">
            <img src="/assets/janeAddamsPics/JaneAddams.jpg" class="img-responsive" alt="CLETeenHack CLETeenVote Cleveland High School Inclusive Hackathon. AT&T. We Can Code IT."/>
        </div>
    </div>

        
                                        <!-- Kendale/Jamir-->
                                        
             <!--election-->
            <div class="row" >
                <div class="col-md-9">
                    <!-- enter header box contents below-->
                    <h1>2016 Election</h1>
                </div>
                <div class="col-md-3">
                    <!--vote now image here-->
                    
              <!-- Vote Now Button -->
                  <a href="/votes/new"> <!-- link to vote now page -->
                      <img src="/assets/janeAddamsPics/Vote-Button-000026017796_Small.jpg" class="img-responsive"/> 
                  </a>
         
                </div>
            </div>
            
            
            <!--This is where the party title and 3 candidates go-->
            <div class="row">
             
                 <div class="col-md-12">
                   <h1> Democrat
                   </h1>
                 </div>
             
                 <div class="col-md-2 col-md-offset-2">
                 <!--enter candidate picture below-->  
                 <img src="/assets/janeAddamsPics/SandersBernie.jpg" class="img-responsive" alt="Bernie Sanders"/>
                 </div>
                
                 <div class="col-md-2">
                 <!--enter candidate picture below-->  
                 <img src="/assets/janeAddamsPics/hillary clinton.jpg" class="img-responsive" alt="Hillary Clinton"/>
                 </div>
             
                 <div class="col-md-2">
                 <!--enter candidate picture below-->  
                 <img src="/assets/janeAddamsPics/LincolnChafee.jpg" class="img-responsive" alt="Lincoln Chafee"/>
                 </div>
            
                <div class="col-md-2">
                    <img src="/assets/janeAddamsPics/WebbJim.jpg" class="img-responsive" alt="Jim Webb"/> 
                </div>
                
                <div class="col-md-2">
                    <img src="/assets/janeAddamsPics/OMalleyMartin.jpg" class="img-responsive" alt="Martin O'Malley"/>
                </div>
            
        
            </div><!--end of row-->
     
     
            <!--democrates canidates-->
          
            <div class="row" style= "background-color: white"> 
                <div class="col-md-12">
                   <h1>Republican</h1>
                </div>
            
                <div class="col-md-2 col-md-offset-2">
                <!--enter candidate picture below-->  
                <img src="/assets/janeAddamsPics/TrumpDonald.jpg" class="img-responsive" alt="Donald Trump"/>
                </div>
                
                <div class="col-md-2">
                <!--enter candidate picture on below-->
                <img src="/assets/janeAddamsPics/KasichJohn.jpg"  class="img-responsive" alt="John Kasich"/>
                </div>
                
                <div class="col-md-2">
                <!--enter candidate picture on below-->  
                <img src="/assets/janeAddamsPics/CruzTed.jpg" class="img-responsive" alt="Ted Cruz"/>
                </div>
                
                <div class="col-md-2">
                    <img src="/assets/janeAddamsPics/CarsonBen.jpg"  class="img-responsive" alt="Ben Carson"/>
                </div>
                
                <div class="col-md-2">
                    <img src="/assets/janeAddamsPics/RubioMarco.jpg"  class="img-responsive" alt="Marco Rubio"/>
                </div>
            </div><!--end of row-->
    
                                        <!-- Kendale/Jamir end-->
    
    
    
    
    
    
    
      
    
    
    <hr/>
                                        <!--Daija-->
    
    <div class="row" margin-top="50px";>
            
            <div class="col-md-4">
                
             <img src="/assets/DemvRep.jpg" height="300px" width="270px" class="img-responsive" alt="Voice Your Opinion"/>
             <!--text here-->
             <h1>voice your <br>opinion</h1>
             <p class="copy">For many of us, teens being unable to vote yet may seem unfair,but our voices count.
                Just because of our age difference it doesnt mean we cant be involved in government choices, such as voting.
                You have the oppritunity to reflect on the generations to come</p>
             </div>
            
             <div class="col-md-4">
              
              <img src="/assets/janeAddamsPics/mic.jpg" height="300px" width="250px" class="img-responsive" alt="Learn About Candidates" />
              <h1>learn about <br>the candidates</h1>
              <p class="copy">These are American citizens that are being considered for a position to better our nation by lowing unemployment , making it possible
              for citizens to have health care insurance, lower the rate of poverty and other issues facing our nations future.</p>
             
             </div>
             
             <div class="col-md-4">
             <img src="/assets/voices.jpg" height="300px" width="250px"class="img-responsive" alt="Learn About Issues"/>
               <h1>learn about<br> the issues</h1>
              <p class="copy" >Government Issues are important topics or problems that are debated or discussed by the citizens and legislators of our nation. Examples of our nations issues are bullying , child abuse , unemplyment , voting rights , poverty and hate crimes.</p>
    
            </div>
        </div>
</div><!--closing main container-->
       

<%= link_to 'Admin', rails_admin_path %> |
<%= link_to 'Issues', issues_path %> |
<a href="/api/docs">API Documentation</a>

app/views/home/resources.html.erb
<script type="text/javascript">
document.getElementById('resourcesTab').id = 'selected'
</script>

<!--add your CSS in the style tag-->
<style>
  body{
        background-image: url("/assets/janeAddamsPics/american_flag.jpg");
        background-attachment: fixed; 
      
  } 
</style>

<!--big resource picture banner here-->
<div class="row">
	<div class="col-md-12" align="center">
	    <img src="/assets/janeAddamsPics/resources.png" class="img-responsive" alt="Voting Resources" height="380" border="10"/>
	</div>
</div></br>
    
     <div class="row">
        
        <div class="col-md-4">
          <!--enter candidate picture below-->  
         <center>
         <a href="http://boe.cuyahogacounty.us/en-us/my-polling-location.aspx">
            <img src="/assets/janeAddamsPics/vote 2012.jpg" class="img-responsive" alt="Polling Locations"  height="78" alt="Cuyahoga County Polling Locations"/>
         <h4><b>where to vote</b></h4></a>
         </center>
        </div>
        <div class="col-md-4">
          <!--enter candidate picture on below-->
          <center>
          <a href="http://www.dmv.org/oh-ohio/voter-registration.php">
                  <img src="/assets/janeAddamsPics/registertovote.png" height="78" class="img-responsive" alt="Ohio Voter Registration"/>
        
         <h4><b>How to register</b></h4></a></center>
        </div>
        <div class="col-md-4">
          <!--enter candidate picture on below-->  
        <center>
        <a href="http://www.wikihow.com/Vote">
        <img src="/assets/janeAddamsPics/howtovote.jpg"  height="78" alt="how to vote" class="img-responsive" />
        
         <h4><b>How to vote</b></h4></a></center>
        </div>
    </div>

     <div class="row">
        
        <div class="col-md-4">
          <!--enter candidate picture below-->  
         
        <center>
        <a href="http://www.newsnet5.com/www.newsnet5.com/news/political/who-are-the-candidates-for-president-of-the-united-states">
            <img src="/assets/janeAddamsPics/candidates.jpg" height="78" class="img-responsive"  alt="2016 Political Candidates"/>
         <h4><b>Who are the candidates</b></h4></a></center>
        </div>
        <div class="col-md-4">
          <!--enter candidate picture on below-->  
        <center><a href="http://ivn.us/2014/09/26/50-reasons-why-you-should-vote/">
        <img src="/assets/janeAddamsPics/why_vote.png" height="78" class="img-responsive" alt="Why Vote"/>
         <h4><b>Why should I vote</b></h4></a></center>
        </div>
        <div class="col-md-4">
          <!--enter candidate picture on below-->  
        <center>
        <a href="http://www.usatoday.com/pages/interactives/elections-results-primaries-2016/#/">
        <img src="/assets/janeAddamsPics/bigstock.jpg" height="78" class="img-responsive" alt="Primaries"/>
         
         <h4><b>Results of the Primaries</b></h4></a>
         </center>
        </div>
    </div>