config/routes.rb
Rails.application.routes.draw do
  resources :contact
  get 'contact/index' => 'contact#index'

  resources :about
  get 'about/index' => 'about#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :issues, only: [:show, :index]
  resources :ballots, only: [:show, :index]
  resources :votes, only: [:new, :create]
  root 'home#index'
  resources :registrations
  get 'resources' => 'home#resources'
  
  resources :votes, only: [:index]  
  get 'votes/results' => 'votes#results'
  get 'votes/thanks_for_voting' => 'votes#thanks_for_voting'
  
  namespace :admin do
    resources :issues
  end

  namespace :api do
    resources :issues
    resources :votes
    resources :voters
    resources :schools
  end

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :issue
  has_many :votes
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :issue_type
  has_many :choices
  has_many :issue_links
end

app/models/issue_link.rb
class IssueLink < ActiveRecord::Base
  belongs_to :issue
end

app/models/issue_type.rb
class IssueType < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voter
  belongs_to :choice
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  belongs_to :school
  has_many :votes

  def self.build_authenticated
    create!(authenticated: true, registration_number: RegistrationNumber.next)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/api/votes_controller.rb
class Api::VotesController < ApplicationController
  def index
    votes = Issue.find(params[:issue_id]).choices.flat_map { |c| c.votes }
    render json: votes
  end

  def create
    voter = Voter.find_by!(registration_number: params[:vote][:registration_number])
    choice = Choice.find(params[:vote][:choice_id])
    render json: Vote.create!(voter_id: voter.id, choice_id: choice.id), status: 201
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ballots_controller.rb
class BallotsController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    @issue = Issue.find(params[:id])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
                         .all
  end

  def show
    
    @issue = Issue.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    if session[:voter]
      redirect_to action: 'show', id: 1
    else
      # renders the registration page
      @voter = Voter.new
      @schools = School.all.map { |s| [s.name, s.id] }
    end
  end

  def create
    # 1. Try submitting the test form at /registrations/new and hitting this breakpoint. (explore the 'params' variable)
    # binding.pry

    voter = nil

    # 2. Implement the 'unauthenticated voter' scenario - where the voter needs to be created without a registration number
    if registration_number.blank?
      voter = Voter.create!(voter_params.merge(registration_number: RegistrationNumber.next))
    else
      # 3. Implement the 'authorized voter' scenario - where the voter has a valid registration number.
      voter = Voter.find_by(registration_number: registration_number, school_id: voter_params[:school_id])
      voter.update_attributes!(voter_params)
    end

    # 4. Store the registered user in 'session' (we can discuss what session is)
    session[:voter] = voter
    redirect_to action: 'show', id: 1
  end

  # renders the success page
  def show
    # TODO - Get the registered user from session if present
    @voter = session[:voter]
  end

  private

  def registration_number
    params[:voter][:registration_number]
  end

  def voter_params
    params.require(:voter).permit(:school_id, :gender, :school_year, :will_be_eighteen)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new

    unless session[:voter]
      redirect_to new_registration_path
    else
      @voter = Voter.find_by(session[:voter]['id'])
      @issues = Issue.all
      @national_issues = Issue.joins(:issue_type)
                              .where(issue_types: {national: true})
                              .all
      @state_issues = Issue.joins(:issue_type)
                           .where(issue_types: {state: true})
                           .all
    end
  end
  def create
    voter = Voter.find(params[:voter_id])
    voter.votes.destroy_all
    if issue_params
      issues = Issue.where(id:params[:issue].keys)
      choices = issues.map{|i|i.choices.where(id:params[:issue][i.id.to_s])}.flatten
      choices.each do |choice|
        issue_id = choice.issue_id.to_s
        Vote.create!(
          voter_id: voter.id,
          choice_id: choice.id,
          understand_this: understand_this_params[issue_id],
          care_about_this: care_about_this_params[issue_id]
        )
      end
    end
  end
  def thanks_for_voting
  end

  def results
    @issues = Issue.all
    @national_issues = Issue.joins(:issue_type)
                            .where(issue_types: {national: true})
                            .all
    @state_issues = Issue.joins(:issue_type)
                         .where(issue_types: {state: true})
  end

  private

  def issue_params
    params.require(:issue)
  end

  def understand_this_params
    params.require(:understand_this)
  end

  def care_about_this_params
    params.require(:care_about_this)
  end

  def index
    @issues = Issue.all
  end

  def voter
    Voter.find_by(session[:voter]['id'])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/api/issues_helper.rb
module Api::IssuesHelper
end

app/helpers/api/voters_helper.rb
module Api::VotersHelper
end

app/helpers/api/votes_helper.rb
module Api::VotesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/confirm.html.erb
$.alert({
    title: 'Are you sure? ',
    content: 'Do you still want to vote for ____!',
    confirm: function(){
        $.alert('Confirmed!'); // shorthand.
    }
});

<h1>Your vote has been recorded!</h1> 

app/views/votes/create.html.erb
<h1>Thanks for Voting!</h1>

<!-- BOOTSTRAP MODAL WAS HERE. REMOVED-->
<!--http://www.w3schools.com/bootstrap/bootstrap_modal.asp -->
<div class="container-fluid"><!--start container-->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Share the Vote!</h4>
        </div>
        <div class="modal-body">
          <div class="col-md-8 "><!--start div for sharing vote-->
              <img src="/assets/Lakewood/I-Voted-Button-Web-Version.jpg" class="img-responsive" alt="I voted in CLETeenHack!"/>
          </div>
           <div class="col-md-4">
            <p><a href="http://twitter.com"> Post to Twitter</a></p>
            <p><a href="http://instagram.com"> Post to Instagram</a></p>
            <p><a href="http://facebook.com"> Post to Facebook</a></p>
            <p><a href="http://tumblr.com"> Post to Tumblr</a></p>
          </div><!--end div-->

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div><!--end modal dialog to share your vote-->

    <div class= "row"> <!-- horizontal container for the website--> 
        <div class= "col-md-6"><!--start col-md-6-->
            <!--add a responsive image-->
            <img src="/assets/Lakewood/collage1.jpg" class="img-responsive" alt="I voted in CLETeenHack CLETeenVote!"/>
         </div><!--end col-md-6-->
         <div class= "col-md-6"><!--start col-md-6-->
            <h2>Let's Make History!</h2><!--heading-->
            <p>Congratulations, You Voted!  </p>
             <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">Share Your Vote!</button>
            <p>Even as young adults, you still have the power to make an impact within your community, whether it be to sign a petition on a cause worth taking account in, or to vote to support what position you are for! Voting is one of the main pillars of our goverment, so when you have a chance to vote, get started!     </p><br />
        </div><!--end col-md-6-->
    </div><!--end row-->
</div><!--end outer container-->

app/views/votes/index.html.erb
<h1>Vote</h1>

<!--Beaumont team to put their vote code here, then send users to thanks_for_voting.html.erb 
with a string stating if vote was recorded or not. ***Please let Mel / WestShore know how you are passing. Query string?
If query string, then what is the name of the param?-->

<!--Mel just threw this in as an example-->
<ul>
<% @issues.each do |issue| %>
  <li>
    <%= link_to issue.title, issue %>
  </li>
<% end %>
</ul>

app/views/votes/new.html.erb
<!--This is our  Ballot Page-->
<h1>Ballot</h1>
<!--Place CSS code in style tag-->
<style>
/*Styling for the font awesome question circle on ballot page, enlarges the size of the question circle on hover*/ 
.fa-question-circle:hover {
	-webkit-transform: scale(1.2);
}

.fa-question-circle {
  transition: font-size 0.35s ease;
}
/*Hides the header and footer on the ballot page so that it looks simplistic */
.navbar-static-top {
  display: none;
}
.footer {
  display: none;
}
</style>

<script>
//Comfirms if user has make at least one selection on the ballot page. If the user has made no selections, they are prompted to make at least one vote
function confirmVote() {
  if (!userVoted()) {
    alert('Please make at least one vote.');
    return false;
  }
  //When user has selected their votes, comfirm their choices and submit
  return confirm('Are you sure you want to submit the following vote?\n' + gatherVotes()) ;
}

function userVoted() {
  return $('input:radio:checked').length > 0;
}

function gatherVotes() {
  var message = "";
  $.each($('input:radio:checked'), function( index, value ) {

    console.log($(value).data('issue-title'));
    message = message +
      $(value).data('issue-title') + ': ' +
      $(value).parent().text().trim() + "\n ";
  });
  return message;
}
</script>
<!--Prompts the user to choose a vote for each National Issue with a radio button. Also adds checkboxes for "I Care" and "I Understand"-->
<%= form_tag votes_path, onsubmit: "return confirmVote();" do %>
  <%= hidden_field_tag 'voter_id', @voter.id %>
  <h1>National Issues</h1>
  <% @national_issues.each do |issue| %>
    <%= fields_for "issue[]", issue do |f| %>
      <div class="row">
        <div class="col-md-12">
          <h2>
            <%= issue.title %>
            <%= link_to issue_path(issue) do %>
              <i class="fa fa-question-circle"></i>
            <% end %>
          </h2>
        </div>
      </div>
    <% end %>
      <div class="row">
        <% issue.choices.each do |choice| %>
          <div class="col-md-3">
            <strong>
              <%= radio_button_tag "issue[#{issue.id}]", choice.id, false, 'data-issue-title'=> issue.title %>
              <%= choice.title %>
            </strong>
          </div>
        <% end %>
        <div class="col-md-3">
          <strong>
            <%= radio_button_tag "issue[#{issue.id}]", '' %>
            None
          </strong>
        </div>
      </div>
      <br>
      <%= check_box 'understand_this', issue.id %> I understand
      <br>
      <%= check_box 'care_about_this', issue.id %> I care about this
  <% end %>
  <br>
  <br>
  
  <!--Prompts the user to choose a vote for each State Issue with a radio button. Also adds checkboxes for "I Care" and "I Understand"-->
  <h1>State Issues</h1>
  <% @state_issues.each do |issue| %>
    <%= fields_for "issue[]", issue do |f| %>
      <div class="row">
        <div class="col-md-12">
          <h2>
            <%= issue.title %>
            <%= link_to issue_path(issue) do %>
              <i class="fa fa-question-circle"></i>
            <% end %>
          </h2>
        </div>
      </div>
    <% end %>
      <div class="row">
        <% issue.choices.each do |choice| %>
          <div class="col-md-3">
            <strong>
              <%= radio_button_tag "issue[#{issue.id}]", choice.id, false, 'data-issue-title'=> issue.title %>
              <%= choice.title %>
            </strong>
          </div>
        <% end %>
        <div class="col-md-3">
          <strong>
            <%= radio_button_tag "issue[#{issue.id}]", '' %>
            None
          </strong>
        </div>
      </div>
      <br>
      <%= check_box 'understand_this', issue.id %> I understand
      <br>
      <%= check_box 'care_about_this', issue.id %> I care about this
  <% end %>
  <br>
  <br>
<!--Button to submit votes-->
  <%= submit_tag "Submit Vote", class: "btn btn-default" %>
<!--If user would like to exit the ballot page without making any votes, this link directs them to the Sample Ballot page-->
  <%= link_to 'Redirect to Sample Ballot', ballots_path %>

<% end %>

app/views/votes/reports.html.erb
<h1>Reports</h1>
<p>Find me in app/views/votes/reports.html.erb</p>

<ul>
<% @issues.each do |issue| %>
  <li>
    <%= link_to issue.title, issue %>
  </li>
<% end %>
</ul>

app/views/votes/results.html.erb
<h1>Results</h1>
<!--add google charts api -->
<%= javascript_include_tag "//www.google.com/jsapi" %> 
<%= javascript_include_tag "application", "chartkick" %>  
   <%@issues.each do |issue| %>
    
    <%teenvotes = {}%>
    <h2><%=issue.title%></h2>
    <% @choices = Choice.where(:issue => issue.id)%>
 
 
    <%@choices.each do |choice| %>
    
      <% @votes = Vote.where(:choice => choice.id)%>
    <%
    teenvotes[choice.title] = @votes.count
    %>
    <%end%>
      <%= pie_chart(teenvotes.stringify_keys) %>
  <%end %>      

app/views/votes/thanks_for_voting.html.erb
<h1>Thanks for Voting!</h1>

<!-- BOOTSTRAP MODAL WAS HERE. REMOVED-->
<!--http://www.w3schools.com/bootstrap/bootstrap_modal.asp -->
<div class="container-fluid"><!--start container-->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Share the Vote!</h4>
        </div>
        <div class="modal-body">
          <div class="col-md-8 "><!--start div for sharing vote-->
              <img src="/assets/Lakewood/I-Voted-Button-Web-Version.jpg" class="img-responsive" alt="I voted in CLETeenHack!"/>
          </div>
           <div class="col-md-4">
            <p><a href="http://twitter.com"> Post to Twitter</a></p>
            <p><a href="http://instagram.com"> Post to Instagram</a></p>
            <p><a href="http://facebook.com"> Post to Facebook</a></p>
            <p><a href="http://tumblr.com"> Post to Tumblr</a></p>
          </div><!--end div-->

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div><!--end modal dialog to share your vote-->

    <div class= "row"> <!-- horizontal container for the website--> 
        <div class= "col-md-6"><!--start col-md-6-->
            <!--add a responsive image-->
            <img src="/assets/Lakewood/collage1.jpg" class="img-responsive" alt="I voted in CLETeenHack CLETeenVote!"/>
         </div><!--end col-md-6-->
         <div class= "col-md-6"><!--start col-md-6-->
            <h2>Let's Make History!</h2><!--heading-->
            <p>Congratulations, You Voted!  </p>
             <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">Share Your Vote!</button>
            <p>Even as young adults, you still have the power to make an impact within your community, whether it be to sign a petition on a cause worth taking account in, or to vote to support what position you are for! Voting is one of the main pillars of our goverment, so when you have a chance to vote, get started!     </p><br />
        </div><!--end col-md-6-->
    </div><!--end row-->
</div><!--end outer container-->